language: node_js

node_js:
  - stable

env:
  - NODE_ENV=production

before_script:
  - rm -rf node_modules
  - rm package-lock.json
  - npm cache clear --force
  - npm install

script:
  - npm run travis

branches:
  only:
    - master

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: master